//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID { get; set; }
        public string Products { get; set; }
        public string TotalAmount { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
