//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPU
    {
        public int ID { get; set; }
        public int ProductGPUID { get; set; }
        public string GPUInterface { get; set; }
        public string GPUManufacturer { get; set; }
        public string GraphicsProcessor { get; set; }
        public string GPUFrequency { get; set; }
        public string GPUTurboFrequency { get; set; }
        public string NumberStreamProcessors { get; set; }
        public string VideoMemory { get; set; }
        public string VideoMemoryType { get; set; }
        public string EffectiveMemoryFrequency { get; set; }
        public string MemoryBandwidth { get; set; }
        public string MemoryBusWidth { get; set; }
        public string DirectXSupport { get; set; }
        public string PowerConnectors { get; set; }
        public string RecommendedPowerSupply { get; set; }
        public string Cooling { get; set; }
        public string NumberFans { get; set; }
        public string VideoCardDimensions { get; set; }
        public string Interfaces { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
