//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDDSSD
    {
        public int ID { get; set; }
        public int ProductHDDSSDID { get; set; }
        public string DiskType { get; set; }
        public string Volume { get; set; }
        public string FormFactor { get; set; }
        public string Interface { get; set; }
        public string Bufer { get; set; }
        public string SequentialReadSpeed { get; set; }
        public string SequentiaWriteSpeed { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
