//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAM
    {
        public int ID { get; set; }
        public int ProductRAMID { get; set; }
        public string RAMSet { get; set; }
        public string RAMVolume { get; set; }
        public string RAMType { get; set; }
        public string RAMFrequency { get; set; }
        public string CASLatency { get; set; }
        public string Timing { get; set; }
        public string SupplyVoltage { get; set; }
        public string ChipLocation { get; set; }
        public string NumberMicrocircuits { get; set; }
        public string CapacityMicrocircuits { get; set; }
        public string TypeMicrocircuits { get; set; }
        public string XMPprofiles { get; set; }
        public string AMPprofiles { get; set; }
        public string Cooling { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
