//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoriesStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialist
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string SpecialistLogin { get; set; }
        public string SpecialistPassword { get; set; }
        public string Email { get; set; }
    }
}
